<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-GB" xml:lang="en-GB"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>1&nbsp; What “learning” means – Decide, Don't Generate</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/ch02.html" rel="next">
<link href="../parts/p1.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-29f00846dc0b6c361e78d357ae7c4662.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-607c349e4ec5b0e049e1f3a4bfbc4a74.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&amp;family=JetBrains+Mono:wght@400;700&amp;family=Source+Serif+4:ital,opsz,wght@0,8..60,400;0,8..60,600;1,8..60,400&amp;display=swap" rel="stylesheet">


<link rel="stylesheet" href="../assets/web/book.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/p1.html">Prerequisites: probability and decisions</a></li><li class="breadcrumb-item"><a href="../chapters/ch01.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">What “learning” means</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Decide, Don’t Generate</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/Mukkandi-Sridhar/JEVBook" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="../Decide,-Don-t-Generate.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="../Decide,-Don-t-Generate.epub">
              <i class="bi bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../front/acknowledgements.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Acknowledgements</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../front/how-to-read.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">How to read this book</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../front/prologue.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prologue: the night shift</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/p1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prerequisites: probability and decisions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch01.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">What “learning” means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Probability, and how a machine learns it</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Calibration: when 0.8 really means 80%</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">From probabilities to actions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/p2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prerequisites: networks, language models and agents</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Deep learning in one chapter</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">How an LLM writes, and structured outputs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">RAG, agents, and where they break</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/p3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Jev in depth</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">System 1 and System 2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Inside Jev: what we know and what we don’t</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">The type system: choice, score, noul</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Testing Jev’s calibration yourself</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">The Jevons paradox of decisions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/p4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The decision layer</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">The bake-off: six ways to make a decision</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Act, review, or escalate</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">A catalogue of decision patterns</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/p5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Building</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch16.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">First calls, and the mock that makes them free</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch17.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">A hybrid agent: Jev decides, the LLM reasons</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch18.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Case study: SOC alert triage</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch19.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">An applications gallery</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch20.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Build your own System One model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch21.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Capstone: a production decision service</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/p6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">What changes now</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch22.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">What changes now</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../back/glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Glossary</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../back/cheatsheets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cheat sheets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../back/bibliography.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bibliography</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../back/index-terms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Index</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../back/about-author.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About the Author</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#start-with-a-rule" id="toc-start-with-a-rule" class="nav-link active" data-scroll-target="#start-with-a-rule"><span class="header-section-number">1.1</span> Start with a rule</a></li>
  <li><a href="#when-rules-run-out" id="toc-when-rules-run-out" class="nav-link" data-scroll-target="#when-rules-run-out"><span class="header-section-number">1.2</span> When rules run out</a></li>
  <li><a href="#let-the-examples-write-the-rules" id="toc-let-the-examples-write-the-rules" class="nav-link" data-scroll-target="#let-the-examples-write-the-rules"><span class="header-section-number">1.3</span> Let the examples write the rules</a></li>
  <li><a href="#so-whats-a-model" id="toc-so-whats-a-model" class="nav-link" data-scroll-target="#so-whats-a-model"><span class="header-section-number">1.4</span> So what’s a “model”?</a></li>
  <li><a href="#meet-the-alerts" id="toc-meet-the-alerts" class="nav-link" data-scroll-target="#meet-the-alerts"><span class="header-section-number">1.5</span> Meet the alerts</a></li>
  <li><a href="#learning-in-its-smallest-form" id="toc-learning-in-its-smallest-form" class="nav-link" data-scroll-target="#learning-in-its-smallest-form"><span class="header-section-number">1.6</span> Learning, in its smallest form</a></li>
  <li><a href="#the-answer-isnt-yes-or-no" id="toc-the-answer-isnt-yes-or-no" class="nav-link" data-scroll-target="#the-answer-isnt-yes-or-no"><span class="header-section-number">1.7</span> The answer isn’t yes or no</a></li>
  <li><a href="#bigger-problems-bigger-models" id="toc-bigger-problems-bigger-models" class="nav-link" data-scroll-target="#bigger-problems-bigger-models"><span class="header-section-number">1.8</span> Bigger problems, bigger models</a></li>
  <li><a href="#where-jev-fits" id="toc-where-jev-fits" class="nav-link" data-scroll-target="#where-jev-fits"><span class="header-section-number">1.9</span> Where Jev fits</a></li>
  <li><a href="#the-map" id="toc-the-map" class="nav-link" data-scroll-target="#the-map"><span class="header-section-number">1.10</span> The map</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/p1.html">Prerequisites: probability and decisions</a></li><li class="breadcrumb-item"><a href="../chapters/ch01.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">What “learning” means</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-ch01" class="quarto-section-identifier"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">What “learning” means</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="epigraph bookbox" data-by="Edsger W. Dijkstra, 1984">
<p>The question of whether a computer can think is no more interesting than the question of whether a submarine can swim.</p>
<div class="quote-by">
— Edsger W. Dijkstra, 1984
</div>
</div>
<p>If you’re trying to get into AI right now, you’ve probably seen these words everywhere:</p>
<p>AI. Machine learning. Deep learning. LLMs. RAG. Agents.</p>
<p>And lately, one more: Jev.</p>
<p>After a while, a quiet thought starts to form:</p>
<p><em>“Do I really need to learn all of this?”</em></p>
<p>Here’s the honest answer. You need less than you fear, but you need it in the right order. These words aren’t a list of separate subjects. They’re chapters of one story, and each one exists because the one before it ran into a wall.</p>
<p>So let’s walk the story. Slowly, with real examples, and without pretending you already know things you don’t.</p>
<div class="goals bookbox">
<div class="box-label">
By the end of this chapter
</div>
<ul>
<li>Tell the difference between a computer following rules and a computer learning.</li>
<li>Say what a <em>model</em> is, in one plain sentence.</li>
<li>Watch a machine learn something, and watch it learn the wrong thing.</li>
<li>Place AI, machine learning, deep learning, LLMs, RAG, agents and Jev on one map.</li>
</ul>
</div>
<section id="start-with-a-rule" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="start-with-a-rule"><span class="header-section-number">1.1</span> Start with a rule</h2>
<p>Your thermostat is a good place to begin.</p>
<p>Somewhere inside it is a line that says, more or less:</p>
<p><em>If the temperature is above 100°F, send an alert.</em></p>
<p>That’s a computer following a rule. I told it exactly what to do. It didn’t figure anything out. It just checks a number and acts.</p>
<p>A surprising amount of software that gets called “AI” is exactly this. A bank that blocks card payments over a limit. A spam filter that bins any email containing “lottery”. An office system that marks you absent if you haven’t badged in by 10 a.m.</p>
<p>And here’s something people rarely say out loud: rules are <em>good</em>. They’re fast, they’re cheap, and when one goes wrong you can open it up and read exactly why. When a rule does the job, use the rule. We’ll come back to this in Chapter 13, where plain rules win more than one round of a contest against much fancier models.</p>
<p>The trouble starts when the world won’t sit still long enough for a rule.</p>
</section>
<section id="when-rules-run-out" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="when-rules-run-out"><span class="header-section-number">1.2</span> When rules run out</h2>
<p>Suppose I want a computer to recognise a cat.</p>
<p>I could try writing the rules. Two eyes. Four legs. Pointed ears. Fur. A tail.</p>
<p>But what if the cat is hiding behind a sofa and you can only see its tail? What if it’s black, on a black cushion, in a dark room? What if it’s a kitten, all head and no legs?</p>
<p>Every answer is another rule. Then every rule needs exceptions, and the exceptions need exceptions.</p>
<p>This isn’t only a cat problem. It’s the everyday problem of anyone who defends a company’s computers.</p>
<p>Picture the security team at Kestrel Logistics, a freight company we’ll follow through the whole book. They want to catch phishing emails, the ones that trick staff into typing a password into a fake page. So someone writes the obvious rule: <em>if an email mentions “password”, flag it.</em></p>
<p>Monday, it flags IT’s own password-reset reminders. So they add an exception.</p>
<p>Wednesday, an attacker writes “passw0rd” with a zero. Another rule.</p>
<p>Friday, the attacker stops writing the word at all and puts it inside an image. Then they drop the text entirely and send a link to a shared document that looks exactly like the real ones.</p>
<div id="fig-rules-vs-examples" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rules-vs-examples-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../figures/ch01/rules-vs-examples.svg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rules-vs-examples-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.1: Two ways to catch phishing. On the left, every new trick forces a new exception, and the list never catches up. On the right, we stop writing rules and show the computer labelled examples instead.
</figcaption>
</figure>
</div>
<p><a href="#fig-rules-vs-examples" class="quarto-xref">Figure&nbsp;<span class="quarto-unresolved-ref">fig-rules-vs-examples</span></a> shows where this ends. The rulebook grows, and it’s always one trick behind, because the attacker gets to read your rules by testing them and you don’t get to read theirs.</p>
</section>
<section id="let-the-examples-write-the-rules" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="let-the-examples-write-the-rules"><span class="header-section-number">1.3</span> Let the examples write the rules</h2>
<p>So we flip the job around.</p>
<p>Instead of telling the computer every rule, we give it a pile of emails where we already know the answer. This one was phishing. This one was fine. This one was phishing. Thousands of them.</p>
<p>And we ask the computer to find the pattern that separates them.</p>
<div class="keyidea bookbox">
<p>That’s machine learning.</p>
</div>
<p>In one sentence: <strong>machine learning is getting a computer to work out the rules itself, from examples where the answer is already known.</strong></p>
<p>You’ve been on the receiving end of this for years. When your bank texts <em>“Did you just spend $640 at an electronics shop in another city?”</em>, no one at the bank wrote a rule about you, that shop and that amount. A system learned what your normal spending looks like from millions of past payments, and this one didn’t fit. When Netflix puts a documentary at the top of your screen, it’s the same move. Nobody wrote “people who watched these three shows want this one”. The pattern came from examples.</p>
</section>
<section id="so-whats-a-model" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="so-whats-a-model"><span class="header-section-number">1.4</span> So what’s a “model”?</h2>
<p>You’ll hear the word <em>model</em> constantly, so let’s pin it down.</p>
<p>When the computer finishes studying the examples, what’s left behind is a thing that takes an input and produces an answer. Give it a new email, it says “phishing” or “fine”. Give it a payment, it says “normal” or “odd”. That thing is the model.</p>
<p>Think of it as a machine with a lot of knobs. Learning is the process of turning those knobs until the machine gets the examples right as often as possible. Once the knobs are set, you stop turning them and put the machine to work, on cases where nobody knows the answer yet. If you already knew the answer, you wouldn’t need the model.</p>
<p>So a <strong>model</strong> is what learning leaves behind: a function whose settings came from examples rather than from a programmer.</p>
</section>
<section id="meet-the-alerts" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="meet-the-alerts"><span class="header-section-number">1.5</span> Meet the alerts</h2>
<p>Before we go further, let’s get our hands on something real enough to learn from.</p>
<p>Kestrel Logistics has a small security operations centre, a SOC. Every system the company runs, from laptops and email to cloud storage and sign-ins, produces <em>alerts</em>: short, messy notes that say “this looked suspicious”. Over four weeks the SOC receives 20,000 of them. That’s about 714 a day, for a handful of analysts.</p>
<p>Most of them are nothing. Only 7.6% turn out to be real attacks.</p>
<p>I’ll be straight with you about one thing: Kestrel Logistics doesn’t exist. Every alert in this book comes from a generator I wrote, and the reason is a good one. With real security data you never know the true answer for sure, and you’re never allowed to publish it anyway. With synthetic data we know exactly what happened in every single case, which means we can check every model’s work, honestly, all book long.</p>
<div class="tryit bookbox" data-lab="ch01">
<div class="box-label">
Try it
</div>
<p>Load the alerts and read one the way an analyst would.</p>
<div id="389fbedb" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> jevkit <span class="im">import</span> soc</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>alerts <span class="op">=</span> soc.load()          <span class="co"># 20,000 synthetic alerts</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">len</span>(alerts), <span class="st">"alerts"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>alerts<span class="sc">.</span>malicious<span class="sc">.</span>mean()<span class="sc">:.1%}</span><span class="ss"> were real attacks"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(alerts.description[<span class="dv">99</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>20000 alerts
7.6% were real attacks
chen.fischer received 21 MFA push requests in 10 minutes; 1 approved. Time 2026-09-22 23:33. Threat intel score: 0.52. 1 related alert in the last 24h. Outside business hours.</code></pre>
</div>
</div>
<p>Every row also carries the truth (<code>malicious</code>), which a real SOC would only learn later, if ever.</p>
<p><a href="https://colab.research.google.com/github/Mukkandi-Sridhar/JEVBook/blob/main/labs/ch01.ipynb">Open this chapter's notebook in Colab →</a></p>
</div>
<p>Look at that alert for a second. Someone received a flood of sign-in approval requests on their phone in the middle of the night, and one was approved. Attackers do exactly this: they spam your phone until you tap “yes” just to make it stop.</p>
<p>Real attack, or not? Hold that question. We’ll come back to this exact alert.</p>
</section>
<section id="learning-in-its-smallest-form" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="learning-in-its-smallest-form"><span class="header-section-number">1.6</span> Learning, in its smallest form</h2>
<p>Let’s make a machine learn something, right now, in about ten lines.</p>
<p>Every alert comes with a <em>threat-intel score</em> between 0 and 1. It’s a rough measure of how bad the outside world thinks the website, address or sender involved is. A reasonable-sounding rule would be: flag the alert if the score is at least some number, call it <em>t</em>.</p>
<p>But which <em>t</em>? 0.3? 0.5? 0.8?</p>
<p>We don’t guess. We try every value from 0 to 1, count how many mistakes each one makes on alerts where we know the answer, and keep the one with the fewest mistakes.</p>
<p>That’s it. That’s learning. Try settings, count mistakes, keep the best.</p>
<div id="023b38f7" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>score <span class="op">=</span> alerts.ioc_score.to_numpy()</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>truth <span class="op">=</span> alerts.malicious.to_numpy()</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> mistakes(t):</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    flagged <span class="op">=</span> score <span class="op">&gt;=</span> t</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    missed <span class="op">=</span> (<span class="op">~</span>flagged <span class="op">&amp;</span> (truth <span class="op">==</span> <span class="dv">1</span>)).<span class="bu">sum</span>()</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    false_alarms <span class="op">=</span> (flagged <span class="op">&amp;</span> (truth <span class="op">==</span> <span class="dv">0</span>)).<span class="bu">sum</span>()</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> missed <span class="op">+</span> false_alarms</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>best <span class="op">=</span> <span class="bu">min</span>(np.arange(<span class="dv">0</span>, <span class="fl">1.01</span>, <span class="fl">0.01</span>), key<span class="op">=</span>mistakes)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"best threshold </span><span class="sc">{</span>best<span class="sc">:.2f}</span><span class="ss">: </span><span class="sc">{</span>mistakes(best)<span class="sc">:,}</span><span class="ss"> mistakes"</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"flag nothing at all:  </span><span class="sc">{</span>mistakes(<span class="fl">1.01</span>)<span class="sc">:,}</span><span class="ss"> mistakes"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>best threshold 0.90: 1,487 mistakes
flag nothing at all:  1,515 mistakes</code></pre>
</div>
</div>
<p>Read those two lines again, because something has gone badly wrong.</p>
<p>The machine searched every threshold and found the one with the fewest mistakes. It picked 0.90, which means it flags only the alerts with the very worst scores. Almost nothing gets flagged. And a “strategy” of never flagging anything at all makes only a few more mistakes.</p>
<div id="fig-threshold-search" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-threshold-search-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../figures/ch01/threshold-search.svg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-threshold-search-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.2: Every possible threshold, and the mistakes it makes. Low thresholds drown the team in false alarms; high ones miss attacks. The total bottoms out at the far right, barely below the dashed line for “flag nothing at all”.
</figcaption>
</figure>
</div>
<p><a href="#fig-threshold-search" class="quarto-xref">Figure&nbsp;<span class="quarto-unresolved-ref">fig-threshold-search</span></a> shows why. There are so many harmless alerts that every false alarm costs the rule more than a missed attack helps it. So the search slides the threshold up and up until it has almost stopped raising alarms. Of 1,515 real attacks, the “best” rule catches 73.</p>
<div class="keyidea bookbox">
<p>The machine learned exactly what we asked. We asked the wrong question.</p>
</div>
<p>This is the most useful failure in the whole book, and it hides two separate problems.</p>
<p>The first: we treated every mistake as equal. But letting a real attacker walk in and bothering an analyst for five minutes aren’t equal mistakes, not even close. Chapter 4 fixes this properly.</p>
<p>The second is quieter, and it’s the one this book is really about. We forced the answer to be <em>yes</em> or <em>no</em>.</p>
<div class="breaks bookbox">
<div class="box-label">
Where this breaks
</div>
<p>A learned model only knows the world its examples came from. If attackers invent a trick that isn’t in the training data, the model has never seen it, and it won’t tell you that it hasn’t. Its answer will look just as confident as always. Labels can be wrong too: analysts disagree, and some attacks are never discovered, so they sit in the data marked “fine”. A model will happily learn those mistakes as if they were truth.</p>
</div>
</section>
<section id="the-answer-isnt-yes-or-no" class="level2" data-number="1.7">
<h2 data-number="1.7" class="anchored" data-anchor-id="the-answer-isnt-yes-or-no"><span class="header-section-number">1.7</span> The answer isn’t yes or no</h2>
<p>Let’s look at the same data from a different angle. Instead of asking “attack or not?”, let’s ask: <em>among alerts with a given score, how many turned out to be attacks?</em></p>
<div id="fig-not-yes-no" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-not-yes-no-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../figures/ch01/not-yes-no.svg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-not-yes-no-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.3: Group the alerts by threat-intel score and count how many were real attacks. The share climbs steadily from 2% to 62%. Even at the very top, plenty of alerts are harmless, and even at the bottom, a few are attacks.
</figcaption>
</figure>
</div>
<p><a href="#fig-not-yes-no" class="quarto-xref">Figure&nbsp;<span class="quarto-unresolved-ref">fig-not-yes-no</span></a> is the picture I want you to keep.</p>
<p>There’s no clean line where alerts switch from harmless to dangerous. Among the lowest-scoring alerts, about 2% were attacks. That sounds tiny, but that bucket holds 7,270 alerts, so it’s well over a hundred real attacks hiding among the quietest-looking noise. Among the highest-scoring alerts, 62% were attacks. Which means more than a third of the scariest-looking ones were nothing.</p>
<p>So what do we honestly know about an alert with a score of 0.55?</p>
<p>Not “it’s an attack”. Not “it’s fine”. What we know is: <em>about one in five alerts like this one is an attack.</em></p>
<p>That number, a chance, carries far more than a yes or a no. It tells the analyst how worried to be. It lets you sort the queue so the likeliest attacks come first. And, as you’ll see in Chapter 4, it lets you set your line in the right place once you’ve decided what each kind of mistake costs.</p>
<div class="keyidea bookbox">
<p>A good model doesn’t just answer. It says how sure it is, and it’s right about how sure it is.</p>
</div>
<p>That last part, being <em>right about how sure it is</em>, has a name, and a whole part of this book to itself. For now, just notice that it’s a very different goal from “make the fewest mistakes”.</p>
<div class="threshold bookbox">
<div class="box-label">
Set the threshold
</div>
<p>A missed attack costs Kestrel roughly ten times what a false alarm costs. Should the threshold on the threat-intel score go <em>up</em> from 0.90 or <em>down</em>? Make a guess before you read on.</p>
<p>(Down, a long way. When a miss hurts more, you accept more false alarms to avoid one. Chapter 4 turns that intuition into a formula.)</p>
</div>
</section>
<section id="bigger-problems-bigger-models" class="level2" data-number="1.8">
<h2 data-number="1.8" class="anchored" data-anchor-id="bigger-problems-bigger-models"><span class="header-section-number">1.8</span> Bigger problems, bigger models</h2>
<p>Our threat-intel rule had it easy: someone handed it a single useful number. A photo is millions of pixels, and an email is a string of words. Nobody can hand-write the features for “this sounds like a scam”. So the next step was models that learn their own features, in many stacked layers. That’s <strong>deep learning</strong> (Chapter 5).</p>
<p>Train a very large deep-learning model on a huge amount of text, with one simple task, guess the next word, and it picks up grammar, facts and even some reasoning along the way. That’s a <strong>large language model</strong>, an LLM (Chapter 6).</p>
<p>LLMs know a lot about the world and nothing about <em>your</em> world, so we let them look things up before answering. That’s <strong>retrieval-augmented generation</strong>, or RAG. And once a model can read, the next wish is for it to <em>do</em> things: check a log, block an account, look at what happened, decide what to do next. A model working in that loop is an <strong>agent</strong> (Chapter 7).</p>
</section>
<section id="where-jev-fits" class="level2" data-number="1.9">
<h2 data-number="1.9" class="anchored" data-anchor-id="where-jev-fits"><span class="header-section-number">1.9</span> Where Jev fits</h2>
<p>Watch an agent work for a while and you notice something.</p>
<p>Most of its steps aren’t writing essays. They’re small decisions. Is this alert real? Which queue does this ticket go in? Is this action safe to take? Did that tool call work? Hundreds of little judgements, each with a known set of possible answers.</p>
<p>For each of those, the usual approach today is to ask an LLM, get a paragraph back, and then write code to dig the answer out of the paragraph. It works. It’s also a bit like hiring a novelist to tick a checkbox.</p>
<div id="fig-generate-vs-decide" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-generate-vs-decide-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../figures/ch01/generate-vs-decide.svg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-generate-vs-decide-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.4: The same question, two ways. An LLM writes its answer out, piece by piece, and your code has to read the sentence. A decision model returns the answer as data, with a probability for every option, in one pass.
</figcaption>
</figure>
</div>
<p>In September 2026, a start-up called TypeSafe AI released a model built for exactly those checkbox moments. It’s called <strong>Jev</strong>. It doesn’t write text at all. You give it the situation and a typed question, like “pick one of these labels” or “is this true, yes or no”, and it gives back the answer as data, with a probability attached to every option (<a href="#fig-generate-vs-decide" class="quarto-xref">Figure&nbsp;<span class="quarto-unresolved-ref">fig-generate-vs-decide</span></a>). TypeSafe calls it a <em>System One</em> model, after the fast, intuitive kind of thinking described by the psychologist Daniel Kahneman, as opposed to slow, deliberate <em>System Two</em> thinking <span class="citation" data-cites="kahneman2011">(<a href="#ref-kahneman2011" role="doc-biblioref">Kahneman 2011</a>)</span>. Part III takes Jev apart properly.</p>
<p>One thing you should know now, because it shapes every page that follows. I didn’t have access to the Jev API while writing this book. So everywhere you see Jev answer a question, the answer comes from <code>jev-mock-synthetic</code>, a stand-in I built that speaks Jev’s exact public interface through TypeSafe’s official Python library. The code is real. The numbers are synthetic, and every one of them is labelled that way.</p>
<p>Here’s your first question to it. Same alert as before, the flood of sign-in requests at night.</p>
<div id="e539d68a" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> typesafe_sdk <span class="im">import</span> Noul, TypeSafeClient</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> jevkit <span class="im">import</span> MockJevTransport</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>client <span class="op">=</span> TypeSafeClient(api_key<span class="op">=</span><span class="st">"mock"</span>,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>                        transport<span class="op">=</span>MockJevTransport())</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> client.system_one(</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    state<span class="op">=</span>alerts.description[<span class="dv">99</span>],</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    questions<span class="op">=</span>{<span class="st">"attack"</span>: Noul(</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>        instructions<span class="op">=</span><span class="st">"Is this alert a real attack?"</span>)},</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(r.model, <span class="bu">round</span>(r.nouls[<span class="st">"attack"</span>].noul, <span class="dv">2</span>))</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"really an attack?"</span>, <span class="bu">bool</span>(alerts.malicious[<span class="dv">99</span>]))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>jev-mock-synthetic 0.68
really an attack? False</code></pre>
</div>
</div>
<p>It thinks it’s probably an attack. It wasn’t. And that’s not a bug in the story, it’s the story.</p>
<p>A probability of 0.68 isn’t a promise. It’s a claim that among alerts like this one, roughly two out of three are attacks. This one happened to be in the other third. Whether a model’s “0.68” really does mean two out of three is something we can <em>test</em>, and we will, in Chapter 3 for ordinary models and in Chapter 11 for Jev.</p>
<div class="bookquote bookbox" data-by="George E. P. Box, statistician, 1979">
<p>All models are wrong, but some are useful.</p>
<div class="quote-by">
— George E. P. Box, statistician, 1979
</div>
</div>
</section>
<section id="the-map" class="level2" data-number="1.10">
<h2 data-number="1.10" class="anchored" data-anchor-id="the-map"><span class="header-section-number">1.10</span> The map</h2>
<p>So instead of memorising AI, ML, deep learning, LLMs, RAG, agents and Jev as seven separate things, think of them as a story.</p>
<p>We wanted computers to do intelligent things. Rules weren’t enough, so we taught machines from examples. As problems got harder, our models got bigger and started learning their own features. Some of them learned language. We gave them documents to read, then tools to use.</p>
<p>And now, inside those tools and loops, we’re finding that most of the work is <em>deciding</em>. Quickly, cheaply, and with an honest sense of how sure we are.</p>
<div id="fig-ai-story-map" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ai-story-map-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../figures/ch01/ai-story-map.svg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ai-story-map-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.5: The story so far. Each step exists because the one before it hit a wall. System One models like Jev branch off deep learning and slot into the “decide” step of an agent.
</figcaption>
</figure>
</div>
<p>That’s the map (<a href="#fig-ai-story-map" class="quarto-xref">Figure&nbsp;<span class="quarto-unresolved-ref">fig-ai-story-map</span></a>).</p>
<p>You don’t need to understand every box today. Just know where we’re going. The next three chapters stay down at the bottom-left corner of this map on purpose, because everything above it, Jev included, is built on one idea we’ve only just met: a model’s answer should be a probability, and the probability should be honest.</p>
<div class="exercises bookbox" data-lab="ch01">
<div class="box-label">
Exercises
</div>
<p><a href="https://colab.research.google.com/github/Mukkandi-Sridhar/JEVBook/blob/main/labs/ch01.ipynb">Open this chapter's lab in Colab →</a></p>
<ol type="1">
<li>Name one system you use every week that follows rules, and one that learned from examples. What gave it away?</li>
<li>In the lab, swap the threat-intel score for <code>prior_alerts_24h</code> (how many related alerts fired in the last day). Which threshold makes the fewest mistakes now? Is that rule any more <em>useful</em>?</li>
<li>Our best rule made 1,487 mistakes and caught almost nothing. Write one sentence describing the question you <em>wish</em> we had asked the machine instead.</li>
<li>Look at <a href="#fig-not-yes-no" class="quarto-xref">Figure&nbsp;<span class="quarto-unresolved-ref">fig-not-yes-no</span></a>. If you could only review 300 alerts a day, how would you pick which 300? What would you need to know that the chart doesn’t show?</li>
</ol>
</div>
<div class="nexthook bookbox">
<p>Next: that “how likely” idea. It sounds like a small change. It turns out to be the most important idea in the book, and it hides a trap that fools doctors, judges and security teams alike.</p>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-kahneman2011" class="csl-entry" role="listitem">
Kahneman, Daniel. 2011. <em>Thinking, Fast and Slow</em>. <span>Farrar, Straus and Giroux</span>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mukkandi-sridhar\.github\.io\/JEVBook");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../parts/p1.html" class="pagination-link" aria-label="Prerequisites: probability and decisions">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Prerequisites: probability and decisions</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/ch02.html" class="pagination-link" aria-label="Probability, and how a machine learns it">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Probability, and how a machine learns it</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>